# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fd33fa2394ec8ce3003ada07e812134e4aeefea244357cfbcc1bb43b7fab2dadcadee4450965b000346399db84d5312c25defa9ccb5fbaa7aa38b3d299219f1e

test:
  secret_key_base: d91df1e0f81dc5f0f84b415985cb930fde566089cc1dffa3ed79a3468b68d3383a47aee6b85b08f9857acbfd5ad963d0ee432599cc0b4593ac83cd3dee2fe68b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
